Numerical python--- continuous memory location and multi-dimensional array data

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [3]:
np.array([11,12,13,14,15,16])

array([11, 12, 13, 14, 15, 16])

In [4]:
a=np.array([90,92,93,88,85,47,63])

In [5]:
a

array([90, 92, 93, 88, 85, 47, 63])

In [6]:
a.shape

(7,)

In [7]:
b=np.array([10,20,30,40,50,60])

In [8]:
b

array([10, 20, 30, 40, 50, 60])

In [9]:
b.shape

(6,)

In [10]:
a=np.array([[1,2],[3,4]])

In [11]:
a

array([[1, 2],
       [3, 4]])

In [12]:
a.shape

(2, 2)

In [13]:
b=np.array([[5,6],[7,8],[9,10]])

In [14]:
b

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [15]:
b.shape

(3, 2)

In [16]:
c=np.array([[78,79,74],[56,57,45],[65,89,78]])

In [17]:
c

array([[78, 79, 74],
       [56, 57, 45],
       [65, 89, 78]])

In [18]:
c.shape

(3, 3)

In [20]:
c=np.array([[77,89,54],[59,58,95],[165,189,178],[69,100,45],[96,79,25]])

In [21]:
c

array([[ 77,  89,  54],
       [ 59,  58,  95],
       [165, 189, 178],
       [ 69, 100,  45],
       [ 96,  79,  25]])

In [22]:
c.shape

(5, 3)

In [24]:
c.reshape(3,5)

array([[ 77,  89,  54,  59,  58],
       [ 95, 165, 189, 178,  69],
       [100,  45,  96,  79,  25]])

In [25]:
c.min()

25

In [26]:
c.max()

189

In [27]:
c.reshape(15,1)

array([[ 77],
       [ 89],
       [ 54],
       [ 59],
       [ 58],
       [ 95],
       [165],
       [189],
       [178],
       [ 69],
       [100],
       [ 45],
       [ 96],
       [ 79],
       [ 25]])

In [28]:
c.reshape(1,15)

array([[ 77,  89,  54,  59,  58,  95, 165, 189, 178,  69, 100,  45,  96,
         79,  25]])

In [29]:
#gives the count of number of elements
c.size

15

In [30]:
a.size

4

In [31]:
b.size

6

In [32]:
#gives the number of bytes/memory occupied by each element 32bytes/8bit = 4bytes
c.itemsize

4

In [33]:
#gives the data type

c.dtype

dtype('int32')

In [34]:
d=np.array([[1,2],[3,4],[5,6]],dtype='float64')
d

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [35]:
d.itemsize

8

In [36]:
d.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [37]:
d.shape

(3, 2)

In [38]:
d.dtype

dtype('float64')

In [39]:
#number of dimensions 2 dimension rows*column
d.ndim

2

In [41]:
z=np.arange(5)
z

array([0, 1, 2, 3, 4])

In [44]:
y=np.arange(15)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [46]:
a=y.reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [47]:
a=y.reshape(5,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [48]:
x=np.arange(25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
a=x.reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [50]:
#ndarray multidimensional array
type(a)

numpy.ndarray

In [51]:
import numpy as np
b=np.array([[1.5,2,3],[5.6,4,9]],dtype='float32')
print(b)

[[1.5 2.  3. ]
 [5.6 4.  9. ]]


In [52]:
import numpy as np
b=np.array([[1.5,2,3],[5.6,4,9]],dtype='float32')


In [53]:
b

array([[1.5, 2. , 3. ],
       [5.6, 4. , 9. ]], dtype=float32)

In [54]:

ra=np.array([[55,22,33],[56,44,99]])
ra

array([[55, 22, 33],
       [56, 44, 99]])

In [55]:
#Ravle----operation in which one numpy array can be converted to single row i.e ravel-----2d is converted to 1d
print(ra.ravel())

[55 22 33 56 44 99]


In [56]:
import numpy as np
b=np.array([[1.5,2,3],[5.6,4,9]],dtype='int32')
b

array([[1, 2, 3],
       [5, 4, 9]])

In [59]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
#arange by range

np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
#arange (start,end,skip or jump)
np.arange(10,30,5)


array([10, 15, 20, 25])

In [63]:
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

Broadcasting in Numpy

In [64]:
a=np.array([[1,2,3,4]])
b=np.array([[2,2,2,2]])
a*b

array([[2, 4, 6, 8]])

In [66]:
a=np.array([[1,2,3,4]])
b=2.0
a*b

array([[2., 4., 6., 8.]])

In [70]:
a=np.array([1,5,6,9])
b=np.arange(4)
print(a)
print(b)

[1 5 6 9]
[0 1 2 3]


In [71]:
c=a-b
print(c)

[1 4 4 6]


In [72]:
c=b-a
print(c)

[-1 -4 -4 -6]


In [73]:
#sqaure
b**2

array([0, 1, 4, 9], dtype=int32)

In [78]:
b=np.random.random([2,3])


In [79]:
b

array([[0.42403487, 0.063887  , 0.13138966],
       [0.27556559, 0.34653519, 0.41887603]])

Univeral functions

In [81]:
B=np.arange(3)
B

array([0, 1, 2])

In [82]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [83]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [84]:
C=np.array([4,5,6])
np.add(B,C)

array([4, 6, 8])

Indexing Slicing and Iterating

In [87]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a[2]

2

In [89]:
a[2:5]

array([2, 3, 4])

In [90]:
a[-1]

9

In [91]:
a[-4:]

array([6, 7, 8, 9])

In [92]:
a[-4:-2]

array([6, 7])

In [93]:
d=np.arange(20)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [94]:
#slicing from 5th index till end of the array
d[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [95]:
x=np.array([np.nan,1,2,3,np.nan,6,7,8])
x

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])

In [96]:
np.random.rand(2,2)    #uniform distribution------> similar like random

array([[0.88940866, 0.6176613 ],
       [0.78323924, 0.49952744]])

In [97]:
np.random.rand(2,3)

array([[0.8075432 , 0.7479784 , 0.62687206],
       [0.03274265, 0.46704865, 0.31704663]])

In [98]:
np.random.rand(3,2)

array([[0.3122901 , 0.91356311],
       [0.03917105, 0.04119   ],
       [0.28059401, 0.37050904]])